### ISSUE TITLE
gt,lt, limit query params 

### ISSUE THREAD

**Issue by DenisVK** [greentriangle/react-native-leveldb#2]
Hi,

Is this library support query params such as gt, lt while iterating ?

Thanks.

**Comment by savv** [comment]
Hi Denis, I don't understand your question fully. With leveldb, you can seek to a particular key (using Seek()) and then use Next() & Prev() to navigate lexicographically. Is this what you had in mind?

Prev() is missing, happy to add it ASAP if this is what you meant.

Do you see something else here that is missing?
https://github.com/google/leveldb/blob/master/doc/index.md

**Comment by DenisVK** [comment]
Sorry for not clear question, i am new to LevelDB and just started to learn how it works.

I checked some other libraries (like node level and some RN implementations) and found that they contain method [(createReadStream)](https://github.com/Level/level#createReadStream)  with qt, lt, limit params for tuning search request.

So wonder if it can be done using this library.

**Comment by savv** [comment]
No problem and thanks for writing. At the moment, it's not a goal for this library to provide functionality like what you describe.
