### ISSUE TITLE
Support react native 0.73.0

### ISSUE THREAD

**Issue by jahead** [greentriangle/react-native-leveldb#24]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-leveldb@3.3.5` for the project I'm working on.

This was done to support Android for `react-native v0.73.0`, Upcoming 0.73.0 has a breaking change for android due to AGP

* [Android] Bump to AGP 8.0 https://github.com/react-native-community/discussions-and-proposals/issues/
  *  breaking changes for libraries -> https://developer.android.com/build/releases/gradle-plugin#namespace-dsl
  * https://github.com/facebook/react-native/pull/37019
    example: https://github.com/expo/expo/pull/22609/files#diff-ef1f15fe3a85e91b5b14cecbe065dd88e055f86f9b54c66fbdfd2c40ce95aa4b

see: https://github.com/reactwg/react-native-releases/discussions/64 for more info
let me know if you would accept PRs.

---

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-native-leveldb/android/build.gradle b/node_modules/react-native-leveldb/android/build.gradle
index 4d233b7..c43a7b2 100644
--- a/node_modules/react-native-leveldb/android/build.gradle
+++ b/node_modules/react-native-leveldb/android/build.gradle
@@ -47,7 +47,7 @@ repositories {
 
 android {
   compileSdkVersion safeExtGet('compileSdkVersion', 28)
-
+  namespace 'com.reactnativeleveldb'
   // Used to override the NDK path/version on internal CI or by allowing
   // users to customize the NDK path/version from their root project (e.g. for M1 support)
   if (rootProject.hasProperty('ndkPath')) {
diff --git a/node_modules/react-native-leveldb/android/src/main/AndroidManifest.xml b/node_modules/react-native-leveldb/android/src/main/AndroidManifest.xml
index 9cdec5b..0a0938a 100644
--- a/node_modules/react-native-leveldb/android/src/main/AndroidManifest.xml
+++ b/node_modules/react-native-leveldb/android/src/main/AndroidManifest.xml
@@ -1,4 +1,3 @@
-<manifest xmlns:android="http://schemas.android.com/apk/res/android"
-          package="com.reactnativeleveldb">
+<manifest xmlns:android="http://schemas.android.com/apk/res/android">
 
 </manifest>
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by savv** [comment]
Thanks a lot for your changes. Would you like to open a PR with these changes? Else I can integrate them myself.
